# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/f4bjh/devel/Rf-Test-BJH/hw/freq_front_end/reciproq_freq_meas/reciproq_freq_meas.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
# IP: The module: 'clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/f4bjh/devel/Rf-Test-BJH/hw/freq_front_end/reciproq_freq_meas/reciproq_freq_meas.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/f4bjh/devel/Rf-Test-BJH/hw/freq_front_end/reciproq_freq_meas/reciproq_freq_meas.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/f4bjh/devel/Rf-Test-BJH/hw/freq_front_end/reciproq_freq_meas/reciproq_freq_meas.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/f4bjh/devel/Rf-Test-BJH/hw/freq_front_end/reciproq_freq_meas/reciproq_freq_meas.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
# IP: The module: 'clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/f4bjh/devel/Rf-Test-BJH/hw/freq_front_end/reciproq_freq_meas/reciproq_freq_meas.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/f4bjh/devel/Rf-Test-BJH/hw/freq_front_end/reciproq_freq_meas/reciproq_freq_meas.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/f4bjh/devel/Rf-Test-BJH/hw/freq_front_end/reciproq_freq_meas/reciproq_freq_meas.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
